resource "hcloud_ssh_key" "default" {
  name       = "proxima-sshkey"
  public_key = file("${path.module}/${var.ssh_key_name}.pub")
}

variable "ssh_key_name" {
  type        = string
  default     = "proxima-sshkey"
  description = "SSH key pair generated by Terraform"
}

resource "tls_private_key" "ssh_key" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "local_file" "private_key" {
  content         = tls_private_key.ssh_key.private_key_pem
  filename        = "${var.ssh_key_name}.pem"
  file_permission = "0600"
}
resource "local_file" "public_key" {
  content         = tls_private_key.ssh_key.public_key_openssh
  filename        = "${var.ssh_key_name}.pub"
  file_permission = "0600"
}
