variable "ssh_key_name" {
  type        = string
  default     = "terraform-key-proxima"
  description = "SSH key pair generated by Terraform"
}

resource "tls_private_key" "private_key_pem" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "hcloud_ssh_key" "default_public_key" {
  name       = var.ssh_key_name
  public_key = tls_private_key.private_key_pem.public_key_openssh #file("~/.ssh/id_rsa.pub")

  provisioner "local-exec" {
    command = <<-EOC
    "echo '${tls_private_key.private_key_pem.private_key_pem}' > ./'${var.ssh_key_name}'.pem"
    chmod 400 ./'${var.ssh_key_name}'.pem
    "echo '${tls_private_key.private_key_pem.public_key_openssh}' > ./'${var.ssh_key_name}'.pub"
    EOC
  }
}