---
# Deploys nomad jobs in the directory nomad_jobs

name: deploy_nomad_jobs
on:
  pull_request:
    types: [opened, reopened]
  push:
    branches:
      - main
    paths:
      - 'nomad_jobs/**'

#  workflow_dispatch:
#    inputs:
#      command:
#        description: plan or apply
#        required: false

jobs:
  terraform-code:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./nomad_jobs
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.9
    
      - name: Init
        id: init
        run: terraform init

      - name: Plan
        id: plan
        run: terraform plan

      - name: Apply
        id: apply
        run: terraform apply

      